/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citbyui260.section03.battleship.frames;

import citbyui260.section03.battleship.control.HelpMenuControl;

/**
 *
 * @author John
 */
public class HelpFrame extends javax.swing.JFrame {
    private HelpMenuControl helpMenuControl = new HelpMenuControl();
    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHelpBody = new javax.swing.JPanel();
        jpHelpMenuItems = new javax.swing.JPanel();
        jpButton_The_Board = new javax.swing.JButton();
        jpButton_Computer_Player = new javax.swing.JButton();
        jpButton_Battleship_Game = new javax.swing.JButton();
        jpButton_Hit_Help = new javax.swing.JButton();
        jpButton_Regular_Player = new javax.swing.JButton();
        jpButton_Ship_Placement = new javax.swing.JButton();
        jpButton_How_to_Win = new javax.swing.JButton();
        jpButton_Quit_Help = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battleship Help Menu");

        jpHelpBody.setBackground(new java.awt.Color(51, 255, 51));

        jpHelpMenuItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpButton_The_Board.setText("The Board");
        jpButton_The_Board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_The_BoardActionPerformed(evt);
            }
        });

        jpButton_Computer_Player.setText("Computer Player");
        jpButton_Computer_Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_Computer_PlayerActionPerformed(evt);
            }
        });

        jpButton_Battleship_Game.setText("Battleship Game");
        jpButton_Battleship_Game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_Battleship_GameActionPerformed(evt);
            }
        });

        jpButton_Hit_Help.setText("Hit Help");
        jpButton_Hit_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_Hit_HelpActionPerformed(evt);
            }
        });

        jpButton_Regular_Player.setText("Regular Player");
        jpButton_Regular_Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_Regular_PlayerActionPerformed(evt);
            }
        });

        jpButton_Ship_Placement.setText("Ship Placement");
        jpButton_Ship_Placement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_Ship_PlacementActionPerformed(evt);
            }
        });

        jpButton_How_to_Win.setText("How to Win");
        jpButton_How_to_Win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_How_to_WinActionPerformed(evt);
            }
        });

        jpButton_Quit_Help.setText("Quit Help");
        jpButton_Quit_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpButton_Quit_HelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHelpMenuItemsLayout = new javax.swing.GroupLayout(jpHelpMenuItems);
        jpHelpMenuItems.setLayout(jpHelpMenuItemsLayout);
        jpHelpMenuItemsLayout.setHorizontalGroup(
            jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpButton_Computer_Player)
                    .addComponent(jpButton_Regular_Player)
                    .addComponent(jpButton_Battleship_Game)
                    .addComponent(jpButton_Hit_Help))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpButton_The_Board)
                    .addComponent(jpButton_Ship_Placement)
                    .addComponent(jpButton_How_to_Win)
                    .addComponent(jpButton_Quit_Help))
                .addContainerGap())
        );
        jpHelpMenuItemsLayout.setVerticalGroup(
            jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpMenuItemsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpButton_Battleship_Game)
                    .addComponent(jpButton_The_Board))
                .addGap(17, 17, 17)
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpButton_Regular_Player)
                    .addComponent(jpButton_Ship_Placement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpButton_Computer_Player)
                    .addComponent(jpButton_How_to_Win))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpHelpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpButton_Quit_Help)
                    .addComponent(jpButton_Hit_Help))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Battleship Help Menu");

        javax.swing.GroupLayout jpHelpBodyLayout = new javax.swing.GroupLayout(jpHelpBody);
        jpHelpBody.setLayout(jpHelpBodyLayout);
        jpHelpBodyLayout.setHorizontalGroup(
            jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpBodyLayout.createSequentialGroup()
                .addGroup(jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHelpBodyLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jpHelpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpHelpBodyLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpHelpBodyLayout.setVerticalGroup(
            jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpBodyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpHelpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHelpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHelpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpButton_Quit_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_Quit_HelpActionPerformed
        this.dispose();
    }//GEN-LAST:event_jpButton_Quit_HelpActionPerformed

    private void jpButton_The_BoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_The_BoardActionPerformed
        helpMenuControl.displayBoardHelp();
    }//GEN-LAST:event_jpButton_The_BoardActionPerformed

    private void jpButton_Computer_PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_Computer_PlayerActionPerformed
        helpMenuControl.displayComputerPlayerHelp();
    }//GEN-LAST:event_jpButton_Computer_PlayerActionPerformed

    private void jpButton_Battleship_GameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_Battleship_GameActionPerformed
        helpMenuControl.displayGameHelp();
    }//GEN-LAST:event_jpButton_Battleship_GameActionPerformed

    private void jpButton_Hit_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_Hit_HelpActionPerformed
        helpMenuControl.displayHitHelp();
    }//GEN-LAST:event_jpButton_Hit_HelpActionPerformed

    private void jpButton_Regular_PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_Regular_PlayerActionPerformed
        helpMenuControl.displayRealPlayerHelp();
    }//GEN-LAST:event_jpButton_Regular_PlayerActionPerformed

    private void jpButton_Ship_PlacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_Ship_PlacementActionPerformed
        helpMenuControl.displayLocationHelp();
    }//GEN-LAST:event_jpButton_Ship_PlacementActionPerformed

    private void jpButton_How_to_WinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpButton_How_to_WinActionPerformed
        helpMenuControl.displayWinHelp();
    }//GEN-LAST:event_jpButton_How_to_WinActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HelpFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jpButton_Battleship_Game;
    private javax.swing.JButton jpButton_Computer_Player;
    private javax.swing.JButton jpButton_Hit_Help;
    private javax.swing.JButton jpButton_How_to_Win;
    private javax.swing.JButton jpButton_Quit_Help;
    private javax.swing.JButton jpButton_Regular_Player;
    private javax.swing.JButton jpButton_Ship_Placement;
    private javax.swing.JButton jpButton_The_Board;
    private javax.swing.JPanel jpHelpBody;
    private javax.swing.JPanel jpHelpMenuItems;
    // End of variables declaration//GEN-END:variables
}
