/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citbyui260.section03.battleship.frames;


import citbyui260.section03.battleship.control.HelpMenuControl;
/**
 *
 * @author Boamhome
 */
public class HelpForm extends javax.swing.JFrame {
    private HelpMenuControl helpMenuControl = new HelpMenuControl();

    /**
     * Creates new form HelpForm
     */
    public HelpForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpMenuTitle = new javax.swing.JTextArea();
        boardHelpButton = new javax.swing.JButton();
        gameHelpButton = new javax.swing.JButton();
        livePlayerHelpButton = new javax.swing.JButton();
        howToWinHelpButton = new javax.swing.JButton();
        computerPlayerHelpButton = new javax.swing.JButton();
        hitHelpButton = new javax.swing.JButton();
        locationHelpButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        helpInstructionsBox = new javax.swing.JTextArea();
        quitHelpMenuButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        helpDisplayBox = new javax.swing.JTextArea();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        helpMenuTitle.setColumns(20);
        helpMenuTitle.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        helpMenuTitle.setRows(5);
        helpMenuTitle.setText("Help Menu");
        jScrollPane1.setViewportView(helpMenuTitle);

        boardHelpButton.setText("Board");
        boardHelpButton.setToolTipText("Get Help with the Board");
        boardHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardHelpButtonActionPerformed(evt);
            }
        });

        gameHelpButton.setText("Game");
        gameHelpButton.setToolTipText("Get Help with the Game");
        gameHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameHelpButtonActionPerformed(evt);
            }
        });

        livePlayerHelpButton.setText("Live Player");
        livePlayerHelpButton.setToolTipText("Get Live Player Help");
        livePlayerHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livePlayerHelpButtonActionPerformed(evt);
            }
        });

        howToWinHelpButton.setText("How to Win");
        howToWinHelpButton.setToolTipText("Learn How to Win");
        howToWinHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToWinHelpButtonActionPerformed(evt);
            }
        });

        computerPlayerHelpButton.setText("Computer Player");
        computerPlayerHelpButton.setToolTipText("Get Computer Player Help");
        computerPlayerHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerPlayerHelpButtonActionPerformed(evt);
            }
        });

        hitHelpButton.setText("Hit");
        hitHelpButton.setToolTipText("Show Hit Help");
        hitHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitHelpButtonActionPerformed(evt);
            }
        });

        locationHelpButton.setText("Location");
        locationHelpButton.setToolTipText("Get Location Help");
        locationHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationHelpButtonActionPerformed(evt);
            }
        });

        helpInstructionsBox.setColumns(20);
        helpInstructionsBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        helpInstructionsBox.setRows(5);
        helpInstructionsBox.setText("Please choose which area you need help with. ");
        jScrollPane2.setViewportView(helpInstructionsBox);

        quitHelpMenuButton.setText("Quit Help Menu");
        quitHelpMenuButton.setToolTipText("Quit Help Menu");
        quitHelpMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitHelpMenuButtonActionPerformed(evt);
            }
        });

        helpDisplayBox.setColumns(20);
        helpDisplayBox.setRows(5);
        jScrollPane3.setViewportView(helpDisplayBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(computerPlayerHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(locationHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hitHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boardHelpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gameHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(livePlayerHelpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(howToWinHelpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(quitHelpMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boardHelpButton)
                        .addGap(18, 18, 18)
                        .addComponent(gameHelpButton)
                        .addGap(18, 18, 18)
                        .addComponent(livePlayerHelpButton)
                        .addGap(18, 18, 18)
                        .addComponent(howToWinHelpButton)
                        .addGap(22, 22, 22)
                        .addComponent(computerPlayerHelpButton)
                        .addGap(18, 18, 18)
                        .addComponent(locationHelpButton))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitHelpButton)
                    .addComponent(quitHelpMenuButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardHelpButtonActionPerformed
       helpMenuControl.displayBoardHelp();
    }//GEN-LAST:event_boardHelpButtonActionPerformed

    private void livePlayerHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livePlayerHelpButtonActionPerformed
        helpMenuControl.displayRealPlayerHelp();
    }//GEN-LAST:event_livePlayerHelpButtonActionPerformed

    private void howToWinHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToWinHelpButtonActionPerformed
        helpMenuControl.displayWinHelp();
    }//GEN-LAST:event_howToWinHelpButtonActionPerformed

    private void quitHelpMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitHelpMenuButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_quitHelpMenuButtonActionPerformed

    private void gameHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameHelpButtonActionPerformed
        helpMenuControl.displayGameHelp();
    }//GEN-LAST:event_gameHelpButtonActionPerformed

    private void computerPlayerHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerPlayerHelpButtonActionPerformed
       helpMenuControl.displayComputerPlayerHelp();
    }//GEN-LAST:event_computerPlayerHelpButtonActionPerformed

    private void locationHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationHelpButtonActionPerformed
        helpMenuControl.displayLocationHelp();
    }//GEN-LAST:event_locationHelpButtonActionPerformed

    private void hitHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitHelpButtonActionPerformed
        helpMenuControl.displayHitHelp();
    }//GEN-LAST:event_hitHelpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boardHelpButton;
    private javax.swing.JButton computerPlayerHelpButton;
    private javax.swing.JButton gameHelpButton;
    private javax.swing.JTextArea helpDisplayBox;
    private javax.swing.JTextArea helpInstructionsBox;
    private javax.swing.JTextArea helpMenuTitle;
    private javax.swing.JButton hitHelpButton;
    private javax.swing.JButton howToWinHelpButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton livePlayerHelpButton;
    private javax.swing.JButton locationHelpButton;
    private javax.swing.JButton quitHelpMenuButton;
    // End of variables declaration//GEN-END:variables
}
