/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citbyui260.section03.battleship.frames;

/**
 *
 * @author katiewalker
 */
public class HelpMenu extends javax.swing.JFrame {

    /**
     * Creates new form HelpMenu
     */
    public HelpMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpTitlePanel = new javax.swing.JPanel();
        jpTitle = new javax.swing.JLabel();
        jpMenuBox = new javax.swing.JPanel();
        jpGameHelp = new javax.swing.JButton();
        jpBoardHelp = new javax.swing.JButton();
        jpComputerPlayerHelp = new javax.swing.JButton();
        jpRegularPlayerHelp = new javax.swing.JButton();
        jpShipPlacementHelp = new javax.swing.JButton();
        jpHitHelp = new javax.swing.JButton();
        jpHowToWinHelp = new javax.swing.JButton();
        jpQuit = new javax.swing.JButton();
        jpText = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBody.setBackground(new java.awt.Color(164, 238, 171));
        jpBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpTitlePanel.setBackground(new java.awt.Color(164, 238, 171));
        jpTitlePanel.setToolTipText("");

        jpTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jpTitle.setText("Battleship Help Menu");

        jpMenuBox.setBackground(new java.awt.Color(164, 238, 171));

        jpGameHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpGameHelp.setText("How to Play");
        jpGameHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpGameHelpActionPerformed(evt);
            }
        });

        jpBoardHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpBoardHelp.setText("About the Board");

        jpComputerPlayerHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpComputerPlayerHelp.setText("Computer Player");

        jpRegularPlayerHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpRegularPlayerHelp.setText("Regular Player");

        jpShipPlacementHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpShipPlacementHelp.setText("Ship Placement");

        jpHitHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpHitHelp.setText("How to Make a Hit");

        jpHowToWinHelp.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpHowToWinHelp.setText("How to Win");

        jpQuit.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jpQuit.setText("Quit");

        javax.swing.GroupLayout jpMenuBoxLayout = new javax.swing.GroupLayout(jpMenuBox);
        jpMenuBox.setLayout(jpMenuBoxLayout);
        jpMenuBoxLayout.setHorizontalGroup(
            jpMenuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuBoxLayout.createSequentialGroup()
                .addGroup(jpMenuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGameHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpBoardHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpComputerPlayerHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpRegularPlayerHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpShipPlacementHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpHitHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpHowToWinHelp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpQuit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpMenuBoxLayout.setVerticalGroup(
            jpMenuBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuBoxLayout.createSequentialGroup()
                .addComponent(jpGameHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBoardHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpComputerPlayerHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRegularPlayerHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpShipPlacementHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHitHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHowToWinHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpQuit))
        );

        javax.swing.GroupLayout jpTitlePanelLayout = new javax.swing.GroupLayout(jpTitlePanel);
        jpTitlePanel.setLayout(jpTitlePanelLayout);
        jpTitlePanelLayout.setHorizontalGroup(
            jpTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitlePanelLayout.createSequentialGroup()
                .addGroup(jpTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTitlePanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jpTitle))
                    .addGroup(jpTitlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpMenuBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpText, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpTitlePanelLayout.setVerticalGroup(
            jpTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jpTitle)
                .addGap(18, 18, 18)
                .addGroup(jpTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpMenuBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jpTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpGameHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpGameHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpGameHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jpBoardHelp;
    private javax.swing.JPanel jpBody;
    private javax.swing.JButton jpComputerPlayerHelp;
    private javax.swing.JButton jpGameHelp;
    private javax.swing.JButton jpHitHelp;
    private javax.swing.JButton jpHowToWinHelp;
    private javax.swing.JPanel jpMenuBox;
    private javax.swing.JButton jpQuit;
    private javax.swing.JButton jpRegularPlayerHelp;
    private javax.swing.JButton jpShipPlacementHelp;
    private javax.swing.JScrollPane jpText;
    private javax.swing.JLabel jpTitle;
    private javax.swing.JPanel jpTitlePanel;
    // End of variables declaration//GEN-END:variables
}
