/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citbyui260.section03.battleship.frames;
import citbyui260.section03.battleship.control.HelpMenuControl;

/**
 *
 * @author Shatzi
 */
public class HelpMenuFrame extends javax.swing.JFrame {
       private HelpMenuControl helpMenuControl = new HelpMenuControl();

    /**
     * Creates new form HelpMenuFrame
     */
    public HelpMenuFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHelpBody = new javax.swing.JPanel();
        jpHelpTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpGameHelp = new javax.swing.JButton();
        jpPlayerHelp = new javax.swing.JButton();
        jpWinHelp = new javax.swing.JButton();
        jpAiHelp = new javax.swing.JButton();
        jpLocationHelp = new javax.swing.JButton();
        jpHitHelp = new javax.swing.JButton();
        jpBoardHelp = new javax.swing.JButton();
        jpExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpHelpMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battleship Help Menu");
        setBackground(new java.awt.Color(0, 153, 153));

        jpHelpBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpHelpBody.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jpHelpBodyLayout = new javax.swing.GroupLayout(jpHelpBody);
        jpHelpBody.setLayout(jpHelpBodyLayout);
        jpHelpBodyLayout.setHorizontalGroup(
            jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jpHelpBodyLayout.setVerticalGroup(
            jpHelpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpHelpTitle.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("An Unfortunate Event DeWarped", 0, 18)); // NOI18N
        jLabel1.setText("Battleship Help Menu");

        jpGameHelp.setText("Game Help");
        jpGameHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpGameHelpActionPerformed(evt);
            }
        });

        jpPlayerHelp.setText("Player Help");
        jpPlayerHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpPlayerHelpActionPerformed(evt);
            }
        });

        jpWinHelp.setText("Win Help");
        jpWinHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpWinHelpActionPerformed(evt);
            }
        });

        jpAiHelp.setText("AI Help");
        jpAiHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpAiHelpActionPerformed(evt);
            }
        });

        jpLocationHelp.setText("Location Help");
        jpLocationHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpLocationHelpActionPerformed(evt);
            }
        });

        jpHitHelp.setText("Hit Help");
        jpHitHelp.setToolTipText("");
        jpHitHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpHitHelpActionPerformed(evt);
            }
        });

        jpBoardHelp.setText("Board Help");
        jpBoardHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpBoardHelpActionPerformed(evt);
            }
        });

        jpExit.setText("Exit");
        jpExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGameHelp)
                    .addComponent(jpPlayerHelp)
                    .addComponent(jpWinHelp)
                    .addComponent(jpAiHelp)
                    .addComponent(jpLocationHelp)
                    .addComponent(jpHitHelp)
                    .addComponent(jpBoardHelp)
                    .addComponent(jpExit))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpGameHelp)
                .addGap(5, 5, 5)
                .addComponent(jpPlayerHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpWinHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAiHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLocationHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHitHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBoardHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpExit)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpHelpMessage.setEditable(false);
        jpHelpMessage.setColumns(20);
        jpHelpMessage.setLineWrap(true);
        jpHelpMessage.setRows(5);
        jpHelpMessage.setText("This is the help menu. What would you like to do?");
        jpHelpMessage.setWrapStyleWord(true);
        jpHelpMessage.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jpHelpMessage);

        javax.swing.GroupLayout jpHelpTitleLayout = new javax.swing.GroupLayout(jpHelpTitle);
        jpHelpTitle.setLayout(jpHelpTitleLayout);
        jpHelpTitleLayout.setHorizontalGroup(
            jpHelpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpTitleLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpHelpTitleLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpHelpTitleLayout.setVerticalGroup(
            jpHelpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHelpTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpHelpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHelpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHelpTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpHelpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHelpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jpExitActionPerformed

    private void jpGameHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpGameHelpActionPerformed
        helpMenuControl.displayGameHelp();
    }//GEN-LAST:event_jpGameHelpActionPerformed

    private void jpPlayerHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpPlayerHelpActionPerformed
        helpMenuControl.displayRealPlayerHelp();
    }//GEN-LAST:event_jpPlayerHelpActionPerformed

    private void jpWinHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpWinHelpActionPerformed
        helpMenuControl.displayWinHelp();
    }//GEN-LAST:event_jpWinHelpActionPerformed

    private void jpAiHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpAiHelpActionPerformed
        helpMenuControl.displayComputerPlayerHelp();
    }//GEN-LAST:event_jpAiHelpActionPerformed

    private void jpLocationHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpLocationHelpActionPerformed
        helpMenuControl.displayLocationHelp();
    }//GEN-LAST:event_jpLocationHelpActionPerformed

    private void jpHitHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpHitHelpActionPerformed
        helpMenuControl.displayHitHelp();
    }//GEN-LAST:event_jpHitHelpActionPerformed

    private void jpBoardHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpBoardHelpActionPerformed
        helpMenuControl.displayBoardHelp();
    }//GEN-LAST:event_jpBoardHelpActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jpAiHelp;
    private javax.swing.JButton jpBoardHelp;
    private javax.swing.JButton jpExit;
    private javax.swing.JButton jpGameHelp;
    private javax.swing.JPanel jpHelpBody;
    private javax.swing.JTextArea jpHelpMessage;
    private javax.swing.JPanel jpHelpTitle;
    private javax.swing.JButton jpHitHelp;
    private javax.swing.JButton jpLocationHelp;
    private javax.swing.JButton jpPlayerHelp;
    private javax.swing.JButton jpWinHelp;
    // End of variables declaration//GEN-END:variables
}
